services:
  app:
    build: .
    env_file:
      - .env
    environment:
      HF_HOME: /cache/huggingface
      HF_HUB_CACHE: /cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "1" ]
              capabilities: [ gpu ]
    stdin_open: true
    tty: true
    volumes:
      - ./.docker-workspace:/workspace
      - .:/workspace/SeedDataGen
      - ./.cache/huggingface:/cache/huggingface

  qwen35:
    image: vllm/vllm-openai:latest
    container_name: qwen35
    ipc: host
    stdin_open: true
    tty: true
    ports:
      - "8077:8000"
    volumes:
      - ./.cache/vllm:/workspace/
    environment:
      VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS: "1"
      HF_HOME: /workspace/hf_cache
      HF_HUB_CACHE: /workspace/hf_cache/hub
      HF_XET_HIGH_PERFORMANCE: "1"
      OMP_NUM_THREADS: "4"
      NVIDIA_VISIBLE_DEVICES: "1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "1" ]
              capabilities: [ gpu ]
    command:
      - Sehyo/Qwen3.5-122B-A10B-NVFP4
      - --max-model-len
      - "80000"
      - --max-num-batched-tokens
      - "32768"
      - --max-num-seqs
      - "64"
      - --kv-cache-dtype
      - fp8_e4m3
      - --gpu-memory-utilization
      - "0.94"
      - --enable-prefix-caching
      - --enable-chunked-prefill
      - --mamba-cache-mode
      - align
      - --mamba-block-size
      - "8"
      - --attention-backend
      - FLASHINFER
      - -O3
      - --speculative-config
      - '{"method":"mtp","num_speculative_tokens":2}'
      - --language-model-only
      - --download-dir
      - /workspace/hf_cache
